groups:
  wrkSFfCgAACytuaSaRbboRSwxrQLo0cg:
    client_id: bugtrack_notify
    client_secret: 922DEEF8-BF8D-C548-8986-BB63EFA137E6
  wrkSFfCgAAJSuw8ipJNgSOdDSOJLFhig:
    client_id: bugtrack_notify
    client_secret: 922DEEF8-BF8D-C548-8986-BB63EFA137E6
